// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBrewData():Promise<main.BrewData>;

export function Greet(arg1:string):Promise<string>;

export function StartService(arg1:string):Promise<main.ActionResponse>;

export function StopService(arg1:string):Promise<main.ActionResponse>;
