// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTap(arg1) {
  return window['go']['main']['App']['AddTap'](arg1);
}

export function DeleteLaunchGroup(arg1) {
  return window['go']['main']['App']['DeleteLaunchGroup'](arg1);
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetAppIcons(arg1) {
  return window['go']['main']['App']['GetAppIcons'](arg1);
}

export function GetAvailableServices() {
  return window['go']['main']['App']['GetAvailableServices']();
}

export function GetBrewCasks() {
  return window['go']['main']['App']['GetBrewCasks']();
}

export function GetBrewData() {
  return window['go']['main']['App']['GetBrewData']();
}

export function GetBrewFormulae() {
  return window['go']['main']['App']['GetBrewFormulae']();
}

export function GetBrewTaps() {
  return window['go']['main']['App']['GetBrewTaps']();
}

export function GetDockerContainers() {
  return window['go']['main']['App']['GetDockerContainers']();
}

export function GetLaunchGroups() {
  return window['go']['main']['App']['GetLaunchGroups']();
}

export function GetTapPackageCount(arg1) {
  return window['go']['main']['App']['GetTapPackageCount'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallPackage(arg1, arg2) {
  return window['go']['main']['App']['InstallPackage'](arg1, arg2);
}

export function LaunchGroup(arg1) {
  return window['go']['main']['App']['LaunchGroup'](arg1);
}

export function RemoveTap(arg1) {
  return window['go']['main']['App']['RemoveTap'](arg1);
}

export function RestartGroup(arg1) {
  return window['go']['main']['App']['RestartGroup'](arg1);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function SaveLaunchGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveLaunchGroup'](arg1, arg2, arg3);
}

export function SearchPackages(arg1) {
  return window['go']['main']['App']['SearchPackages'](arg1);
}

export function StartDocker() {
  return window['go']['main']['App']['StartDocker']();
}

export function StartDockerContainer(arg1) {
  return window['go']['main']['App']['StartDockerContainer'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopDockerContainer(arg1) {
  return window['go']['main']['App']['StopDockerContainer'](arg1);
}

export function StopGroup(arg1) {
  return window['go']['main']['App']['StopGroup'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function UpdateAllTaps() {
  return window['go']['main']['App']['UpdateAllTaps']();
}

export function UpdateTap(arg1) {
  return window['go']['main']['App']['UpdateTap'](arg1);
}
