// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTap(arg1:string):Promise<main.ActionResponse>;

export function GetAppIcon(arg1:string):Promise<string>;

export function GetAppIcons(arg1:Array<string>):Promise<Record<string, string>>;

export function GetBrewData():Promise<main.BrewData>;

export function GetBrewTaps():Promise<Array<main.BrewTap>>;

export function GetDockerContainers():Promise<main.ActionResponse>;

export function GetTapPackageCount(arg1:string):Promise<Record<string, number>>;

export function Greet(arg1:string):Promise<string>;

export function InstallPackage(arg1:string,arg2:boolean):Promise<main.ActionResponse>;

export function RemoveTap(arg1:string,arg2:boolean):Promise<main.ActionResponse>;

export function RestartService(arg1:string):Promise<main.ActionResponse>;

export function SearchPackages(arg1:string):Promise<Record<string, any>>;

export function StartDockerContainer(arg1:string):Promise<main.ActionResponse>;

export function StartService(arg1:string):Promise<main.ActionResponse>;

export function StopDockerContainer(arg1:string):Promise<main.ActionResponse>;

export function StopService(arg1:string):Promise<main.ActionResponse>;

export function UpdateAllTaps():Promise<main.ActionResponse>;

export function UpdateTap(arg1:string):Promise<main.ActionResponse>;
