// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTap(arg1) {
  return window['go']['main']['App']['AddTap'](arg1);
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetBrewData() {
  return window['go']['main']['App']['GetBrewData']();
}

export function GetBrewTaps() {
  return window['go']['main']['App']['GetBrewTaps']();
}

export function GetTapPackageCount(arg1) {
  return window['go']['main']['App']['GetTapPackageCount'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallPackage(arg1, arg2) {
  return window['go']['main']['App']['InstallPackage'](arg1, arg2);
}

export function RemoveTap(arg1, arg2) {
  return window['go']['main']['App']['RemoveTap'](arg1, arg2);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function SearchPackages(arg1) {
  return window['go']['main']['App']['SearchPackages'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function UpdateAllTaps() {
  return window['go']['main']['App']['UpdateAllTaps']();
}

export function UpdateTap(arg1) {
  return window['go']['main']['App']['UpdateTap'](arg1);
}
